version: 2

sources:
  - name: raw
    schema: test
    tables:
      - name: sales
        identifier: raw_gz_sales
      - name: product
        identifier: raw_gz_product
      - name: ships
        identifier: raw_gz_ship