version: 2

sources:
  - name: raw
    schema: test
    tables:
      - name: sales
        identifier: raw_gz_sales
        columns:
          - name: pk
            tests:
              - unique:
                pk: Concat(orders_id, '-', products_id)
                  
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            tests:
              - not_null
              - unique
                  
      - name: ships
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
            - not_null
            - unique
                