version: 2

sources:
  - name: raw
    schema: test
    tables:
      - name: sales
        identifier: raw_gz_sales
      - name: product
        identifier: raw_gz_product
        columns:
          - name: product_id
            tests:
              - not_null
              - unique
                  
      - name: ships
        identifier: raw_gz_ship
        columns:
          - name: order_id
            tests:
            - not_null
            - unique
                